apiVersion: apps/v1
kind: Deployment
metadata:
  name: vadad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vadad
  template:
    metadata:
      labels:
        app: vadad
    spec:
      containers:
      - image: okteto.dev/vadad:latest
        name: vadad
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7be2913d-095f-4836-b22d-a12cf1ba599a"
        - name: Vless_Path
          value: "/vl55csdu"
        - name: Vmess_UUID
          value: "7be2913d-095f-4836-b22d-a12cf1ba599a"
        - name: Vmess_Path
          value: "/vlagcs76u"
        - name: Share_Path
          value: "/v2link"
